# Configuration parameters for the script
# The class SimplicialComplexConstructor needs input parameters to be set in the config file.
# Now it can either take a single csv file that contains the information of the graph
# or it can take two files that contain the information of the edges and triangles of the graph.

simplicial_complex_constructor:
   csv_file : "Padgett-Florentine-Families_multiplex.edges"  # Warning: This is a network, the Dirac signal processing is only
                                                             # with D1

save_results_fig : False
